development:
secret_key_base: ENV['SECRET_KEY_BASE']
aws_access_key_id: ENV['AWS_ACCESS_KEY_ID']
aws_secret_access_key: ENV['AWS_SECRET_ACCESS_KEY']
aws_region: ENV['AWS_REGION']
stripe_secret_key: 'sk_test_2JLaEKttmuDtBI642psVvOeO00YYPPCgvL'
stripe_publishable_key: 'pk_test_8Ju8MMwYB5mmIL3aMmZlRkV500VhGhAx0L'